version: '3.7'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - /etc/localtime:/etc/localtime
    networks:
      - grafana-network
    restart: always

  grafana-mysql80:
    image: mysql:8.0
    container_name: grafana-mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
    networks:
      - grafana-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      # - "./grafana/data:/var/lib/grafana"
      - /etc/localtime:/etc/localtime
    depends_on:
      - grafana-mysql80
    networks:
      - grafana-network
    restart: always

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

networks:
  grafana-network:
    # driver: bridge
    external: true